### ISSUE TITLE
SEGMENT_WRITE_KEY_ENDPOINT and WOOPRA_DOMAIN_ENDPOINT not working for endpoints that provide text/plain reponse 

### ISSUE THREAD

**Issue by dkwon17** [che-incubator/devworkspace-telemetry-woopra-plugin#2]
To reproduce the problem, run the following
```
export DEVWORKSPACE_ID=foo
export SEGMENT_WRITE_KEY=foo
export  WOOPRA_DOMAIN_ENDPOINT=https://gist.githubusercontent.com/dkwon17/5845b9cde63abab3305cf877960650bf/raw/fb245dec8d7b75817afb5877505857ef725614b6/my_domain

java -jar target/quarkus-app/quarkus-run.jar 
```

Running the commands above results in this error:
```
2022-02-25 17:14:02,511 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.io.IOException: OK
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:294)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager.tryRequestFromUrl(AnalyticsManager.java:147)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager.setWoopraDomain(AnalyticsManager.java:139)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager.<init>(AnalyticsManager.java:101)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager_Bean.create(Unknown Source)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager_Bean.get(Unknown Source)
        at com.redhat.devworkspace.services.telemetry.woopra.AnalyticsManager_Bean.get(Unknown Source)
        at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Bean.create(Unknown Source)
        at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

This seems to be happening because `DefaultHttpJsonRequest` requires that the endpoint to provide a response header with a context type of `application/json`.

Responses with context type `text/plain` (ex. https://gist.githubusercontent.com/dkwon17/5845b9cde63abab3305cf877960650bf/raw/fb245dec8d7b75817afb5877505857ef725614b6/my_domain) should be supported.

**Comment by ibuziuk** [comment]
@dkwon17 I think we can now close the issue since PR is merged https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin/pull/15

**Comment by dkwon17** [comment]
Sounds good, closing now
